global:
  lowDataMode: true
nri-prometheus:
  config:
    transformations:
      # One or more transformations can be performed here.
      # Options include: add_attributes, rename_attributes, copy_attributes, ignore_metrics
      # https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/add-rename-or-copy-prometheus-attributes
      - description: "Instruqt Metric Exclusion Example for Redis"
        ignore_metrics:
          - prefixes:
            - redis_exporter
            - redis_repl
newrelic-logging:
  fluentBit:
    # Note:
    # This parameter enables the log parser to match cri-o containerd log patterns
    # https://docs.fluentbit.io/manual/installation/kubernetes#container-runtime-interface-cri-parser
    criEnabled: true
    # Note:
    # Enables the ability to exclude pod logs with fluentbit.io/exlude: "true" annotations
    # Only works when lowDataMode: false
    k8sLoggingExclude: "On"
    config:
      lowDataModeFilters: |
        [FILTER]
            Name           kubernetes
            Match          kube.*
            # We need the full DNS suffix as Windows only supports resolving names with this suffix
            # See: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations
            Kube_URL       https://kubernetes.default.svc.cluster.local:443
            Buffer_Size    ${K8S_BUFFER_SIZE}
            K8S-Logging.Exclude ${K8S_LOGGING_EXCLUDE}
            Labels         Off
            Annotations    Off

        [FILTER]
            Name           nest
            Match          *
            Operation      lift
            Nested_under   kubernetes

        [FILTER]
            Name           record_modifier
            Match          *
            Record         cluster_name ${CLUSTER_NAME}
            Allowlist_key  container_name
            Allowlist_key  namespace_name
            Allowlist_key  pod_name
            Allowlist_key  stream
            Allowlist_key  message
            Allowlist_key  log
newrelic-infrastructure:
  common:
    agentConfig:
      # Note:
      # This parameter enables process monitoring on the Kubernetes cluster nodes.
      # It is disabled in some accounts by default.
      # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#enable-process-metrics
      #
      enable_process_metrics: true
  customAttributes:
    # Note:
    # Let's add a custom attribute to all events sent by the Infrastructure agent
    env: instruqt
  # Note:
  # This is slightly different in V3 - formerly integrations_config in V2
  integrations:
    nri-rabbitmq-workshop:
      # Note:
      # Runs auto discovery to find pods with label "component=rabbitmq"
      # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
      discovery:
        command:
          # Use the following optional arguments:
          # --namespaces: Comma separated list of namespaces to discover pods on
          # --tls: Use secure (TLS) connection
          # --port: Port used to connect to the kubelet. Default is 10255
          #
          # Note: Since we're running in K3s, we must modify the port to 10250
          # https://rancher.com/docs/rancher/v2.5/en/installation/requirements/ports/#ports-for-rancher-server-nodes-on-k3s
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port 10250 --tls
          match:
            label.component: rabbitmq
      integrations:
        - name: nri-rabbitmq
          env:
            # using the discovered IP as the hostname address
            HOSTNAME: ${discovery.ip}
            PORT: 15672
            USERNAME: user
            PASSWORD: bitnami
            QUEUES: '["message"]'
          labels:
            role: rabbitmq